// <auto-generated />
using Loolpay.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Loolpay.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260521084829_InitialCreateSqlite")]
    partial class InitialCreateSqlite
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("Loolpay.Models.Store", b =>
                {
                    b.Property<int>("StoreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("store_id");

                    b.Property<string>("Pay")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("pay");

                    b.Property<string>("StoreAddress")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("store_address");

                    b.Property<string>("StoreName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("store_name");

                    b.HasKey("StoreId");

                    b.ToTable("stores");
                });
#pragma warning restore 612, 618
        }
    }
}
